### PR TITLE
tidy up roles; add attribute values for availability

### PR DESCRIPTION
**Pull request by holfordm**
- Tidy up instructions for using LOC relator codes, including drawing
attention to a variance in medieval / Fihrist practice in the treatment
of translators.
- change values of `status` attribute on `availability` to fit with
suggestions for implementing circulation system

### CODE REVIEW

**Comment by andrew-morrison** [comment]
I've made some changes to the availability status (easier then explaining them in comments, but if you disagree they can be reverted.)

The use of "unknown" in Fihrist is in manuscript descriptions which were created by the Arabic Commentaries on the Hippocratic Aphorisms project. They aren't actual holdings, so their availability is indeed unknown.

@holfordm: I'm happy to merge this into master, if you are. I can then ask on the Fihrist mailing list if they have any statuses they want to add (SOAS are keen to use this.)

**Comment by andrew-morrison** [comment]
@holfordm: Would it be OK if next I add in Burkhard's requested two elements and [documentation](https://github.com/bodleian/consolidated-tei-schema/issues/22#issuecomment-458594061), noting that they are for backward compatibility and not necessarily recommended for use with TEI intended for display in one of our catalogue web sites, then we merge this pull request (plus the templates one?), re-generate the RNG, HTML, etc, and call that a release? Say on Wednesday?

**Comment by holfordm** [comment]
Yes, good idea - let's say Wednesday. I'll have another read through for typos, etc, as well

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrew-morrison** [comment]
OK, great.

BTW, is it time to remove the "UNFINISHED DRAFT - IN PROGRESS" from the title? Or maybe add something to introduction saying it will be continually updated as we modify the schema?

**Pull request merged**
