### PR TITLE
Template

### PR DESCRIPTION
**Pull request by holfordm**
add a template record for use by different projects (if people think this is a good idea - it has certainly been requested by cataloguers)

### CODE REVIEW

**Comment by andrew-morrison** [comment]
Looks good. But, as ever, how and when to use msPart complicates things. Perhaps two templates - one for multipart manuscripts, one for single-source - would be better?

If people leave in empty elements, they'll display as labels with no text. Maybe for things like rubric, incipit, etc the comments could say:
```
<!-- insert or delete if not applicable -->
```
Finally, Oxygen will open URLs if you Ctrl+Click on them, which means you can do something like the following:
```
<head><!-- provide a summary if required, see See https://git.io/msdesc#heading --></head>
```
That is a shortened URL pointing to https://bodleian.github.io/consolidated-tei-schema/msdesc.html#heading. Probably not worth it for something as simple as the head element, but for more complicated sections, where you've got examples of different alternatives in the documentation, it might be useful?

**Comment by holfordm** [comment]
question - how do the other catalogues deal with collections? Does this differ from the medieval practice of `title type="collection"`? (and if so - is this something we should think about standardizing?)

**Comment by holfordm** [comment]
commit 7786642647b6c3343641ae52ea28ce567876d53b

**Comment by andrew-morrison** [comment]
Medieval is the only catalogue in which the indexing script populates the collection filter from the `tei:titleStmt/tei:title[@type='collection']`. All the rest, it comes from `tei:msDesc/tei:msIdentifier/tei:collection`. But it isn't a problem for the web site, because they each need their own indexing scripts, to handle other differences.

If you want I could batch convert Medieval to move the collections into `msIdentifier`.

Other than collections in Medieval, `titleStmt` is ignored for indexing and display on the web site. And I did nothing to standardize it when batch converting files for each catalogue. So there is a lot of variation.

For example, all of Georgian looks like this:
```
<titleStmt>
   <title>CATALOGUE OF THE WARDROP COLLECTION ONLINE</title>
   <funder>JISC</funder>
   <principal>Gillian Evison</principal>
</titleStmt>
```
And most of Hebrew looks like this:
```
<titleStmt>
   <title>Digital description of MS. Canonici Or. 109</title>
   <respStmt>
      <resp>Cataloguer</resp>
      <persName>[Name of cataloguer]</persName>
   </respStmt>
</titleStmt>
```
Whereas this is one of Wadham's recently-created Fihirst records:
```
<titleStmt>
   <title>ONLINE CATALOGUE OF THE PERSIAN AND ARABIC MANUSCRIPTS IN THE FERDOWSI LIBRARY, WADHAM COLLEGE, UNIVERSITY OF OXFORD (MINASIAN COLLECTION)</title>
   <funder>Wadham College (University of Oxford)</funder>
   <principal>Ali Mir-Ansari</principal>
   <editor>Mohammad Emami</editor>
</titleStmt>
```
And this is a new Cambridge Fihrist one:
```
<titleStmt>
   <title>Or. 2575</title>
   <funder>CUL</funder>
   <principal/>
</titleStmt>
```
And an old Cambridge Fihrist one:
```
<titleStmt>
   <title>Y. 8</title>
   <funder>JISC</funder>
   <principal>Gillian Evison</principal>
</titleStmt>
```

**Pull request merged**
