### PR TITLE
various updates (see commit details) ahead of TEI symposium

### PR DESCRIPTION
**Pull request by holfordm**

### CODE REVIEW

**Comment by andrew-morrison** [comment]
Regarding `supportDesc/@material`, what about:

* papyrus (used in Medieval)
* vellum (used in Armenian and Fihrist)
* palm_leaf (used in Senmai)
* clay and wood (one each in Medieval)

There are also various types of paper (cotton, bamboo shoot, black, etc) but those can be classed as "chart" and then described in detail in a child `support` element.

There are also 708 `supportDesc` in all the TEI catalogues which will be invalid because they don't have a material element.

**Comment by holfordm** [comment]
Clay and wood I am happy to be classed as other. Papyrus should be included. Vellum I think should be the same as parchment. We might need to double check with Yasmin and Gillian.

I imagine that all the errors are composite manuscripts where the material differs between parts and so the supportDesc of the msDesc element cannot have a material attribute. If we could have a more sophisticated schematron rule that did not require the attribute in msDesc as long as it was present in all msPart elements, it might fix this. A similar refinement to the rule requiring languages would also be useful.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by holfordm** [comment]
hi @andrew-morrison - do I need to make any changes to this? If possible it would be good to have the changes in place by 29 April when we have a new cataloguer starting - I'm keen to minimize the possibilities for error as much as possible!

**Comment by andrew-morrison** [comment]
Sorry, I have been meaning to review this and merge. The conflicts are, I think, because this "updates"  branch was merged once before, but I neglected to delete it at that point, so when work was resumed on it later it was behind the master branch. I'll try and sort it out tomorrow, and do a release.

**Pull request merged**
